site_name: Two Scoops of Django 3.x 中文版
site_author: caoqianming
theme: readthedocs

repo_url: https://github.com/caoqianming/django3x-best-practice
remote_branch: main
edit_uri: 'edit/main/docs/'

nav:
  - 前言: 'index.md'
  - 作者注: 'authors_notes.md'
  - 简介: 'information.md'
  - 代码格式: 'coding_style.md'
  - Django最佳环境配置: 'optimal_env.md'